title: Jack Beeler
logo: /assets/img/Profile.jpg
description: Computer Science B.S. | Mercedes-Benz | Esri | Cryptocurrency | Coding
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
paginate: 10
per_page: 20
paginate_path: "/page:num/"
author: Jack Beeler


disqus_shortname:
google_analytics:


plugins:
  - jekyll-paginate
  - jekyll-gist



compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
