title: Jack Beeler
logo: /assets/img/Profile.jpg
description: Computer Science B.S.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
paginate: 10
per_page: 20
paginate_path: "/page:num/"



plugins:
  - jekyll-paginate
  - jekyll-gist



compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
